[project]
name = "de25-lab2-azure-antone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas-stubs~=3.0.5",
]

[tool.uv.workspace]
members = [
    "frontend",
    "backend",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "kagglehub>=1.0.2",
]
